server:
  port: 9000
  address: 0.0.0.0
  error:
    whitelabel:
      enabled: false

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: filebench
      username: user
      password: password
      auto-index-creation: true
    codec:
      max-in-memory-size: 10MB
  cache:
    type: hazelcast

id:
  length: 9

validation:
  bench:
    nameRegex: "^[a-zA-Z0-9 ]+$"
    nameRequired: true
    nameMinLength: 4
    nameMaxLength: 24
    descriptionRegex: "^[a-zA-Z0-9 ]+$"
    descriptionReqired: false
    descriptionMinLength: 0
    descriptionMaxLength: 255
    expirationMinDuration: 1H
    expirationMaxDuration: 24H
  file:
    nameRegex: "^[a-zA-Z0-9 ]+$"
    nameRequired: false
    nameMinLength: 4
    nameMaxLength: 24
    descriptionRegex: "^[a-zA-Z0-9 ]+$"
    descriptionReqired: false
    descriptionMinLength: 0
    descriptionMaxLength: 256
    labelRegex: "^[a-zA-Z0-9_]+$"
    labelReqired: false
    labelMinLength: 0
    labelMaxLength: 128

storage:
  local:
    root-dir: files

bench:
  manager:
    expiration-check-time-ms: 1000

file:
  size-max-byte: 1.048.576

hazecast:
  instance: hc-instnace

logging:
  level:
    root: info
    com:
      semihbkgr:
        filebench:
          server: debug
