version: '3.9'

services:
  database:
    image: mysql:5.7
    container_name: file-bench-database
    hostname: mysql
    environment:
      MYSQL_DATABASE: 'filebench'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3306:3306"
    networks:
      - file-bench-server
  filebench:
    build: .
    container_name: file-bench-server
    hostname: filebench
    environment:
      SERVER_PORT: 9000
      DATABASE_USERNAME: 'user'
      DATABASE_PASSWORD: 'password'
      DATABASE_HOSTNAME: 'database'
      DATABASE_PORT: 3306
      DATABASE_SCHEMA: 'filebench'
    ports:
      - "9000:9000"
    networks:
      - file-bench-server

networks:
  file-bench-server:
    driver: bridge
