version: '3.9'

services:
  database:
    image: mysql:5.7
    container_name: file-bench-database
    hostname: mysql
    environment:
      MYSQL_DATABASE: 'filebench'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3306:3306"
    networks:
      - file-bench-server

networks:
  file-bench-server:
    driver: bridge