server:
  port: 9000
  address: 0.0.0.0
  error:
    whitelabel:
      enabled: false
    include-exception: true
    include-message: always

management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  r2dbc:
    username: user
    password: password
    url: r2dbc:mysql://localhost:3306/filebench?tlsVersion=TLSv1.2
    sql:
      schema: sql/schema.sql

token:
  length: 9

storage:
  local:
    root-dir: files

bench:
  max-size: 50000000
  max-file-count: 5
  max-file-size: 5000000
  min-expiration-duration: 1000000
  max-expiration-duration: 10000000
  file:
    max-size: 1000000
  expiration:
    check-duration: 10000
  actuator:
    cache-duration: 30000

logging:
  level:
    root: info
    com:
      semihbkgr:
        filebench:
          server: debug
