server:
  port: 9000
  address: 0.0.0.0
  error:
    whitelabel:
      enabled: false
    include-exception: true
    include-message: always

spring:
  r2dbc:
    username: user
    password: password
    url: r2dbc:mysql://localhost:3306/filebench

id:
  length: 7

storage:
  local:
    root-dir: files

bench:
  manager:
    expiration-check-time-ms: 1000

file:
  size-max-byte: 1.048.576

logging:
  level:
    root: info
    com:
      semihbkgr:
        filebench:
          server: debug
