server:
  port: 9000
  address: 0.0.0.0
  error:
    whitelabel:
      enabled: false
    include-exception: true
    include-message: always

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: filebench
      username: user
      password: password
      auto-index-creation: true
    codec:
      max-in-memory-size: 10MB
  cache:
    type: hazelcast

id:
  length: 7

storage:
  local:
    root-dir: files

bench:
  manager:
    expiration-check-time-ms: 1000

file:
  size-max-byte: 1.048.576

logging:
  level:
    root: info
    com:
      semihbkgr:
        filebench:
          server: debug
