server:
  port: 9000
  address: 0.0.0.0
  error:
    whitelabel:
      enabled: false
    include-exception: true
    include-message: always

management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  r2dbc:
    username: user
    password: password
    url: r2dbc:mysql://localhost:3306/filebench?tlsVersion=TLSv1.2
    sql:
      schema: sql/schema.sql

token:
  length: 9

storage:
  local:
    root-dir: files

bench:
  max-size: 5368709120 #5GB
  max-file-count: 30
  max-file-size: 5000000 #5MB
  min-expiration-duration: 10m
  max-expiration-duration: 1h
  file:
    max-size: 5242880
  expiration:
    check-duration: 20s
  actuator:
    cache-duration: 10s
  metric:
    memory-size-name: bench-memory-size


logging:
  level:
    root: info
    com:
      semihbkgr:
        filebench:
          server: debug
