server:
  port: ${SERVER_PORT}
  address: 0.0.0.0
  error:
    whitelabel:
      enabled: false
    include-exception: true
    include-message: always

management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  r2dbc:
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    url: r2dbc:mysql://${DATABASE_HOSTNAME}:${DATABASE_PORT}/${DATABASE_SCHEMA}?tlsVersion=TLSv1.2
    sql:
      schema: sql/schema.sql

token:
  length: 9

storage:
  local:
    root-dir: files

bench:
  max-size: 5368709120 #5GB
  max-file-count: 30
  max-file-size: 5000000 #5MB
  min-expiration-duration: 10m
  max-expiration-duration: 1h
  file:
    max-size: 5242880
  expiration:
    check-duration: 20s
  actuator:
    cache-duration: 10s

logging:
  level:
    root: error
    com:
      semihbkgr:
        filebench:
          server: warn
