server:
  port: 9000
  address: 0.0.0.0
  error:
    whitelabel:
      enabled: false
    include-exception: true
    include-message: always
    include-stacktrace: on_param
    include-binding-errors: on_param

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: filebench
      username: user
      password: password
      auto-index-creation: true
    redis:
      repositories:
        enabled: false
      hostname: localhost
      port: 6379
    codec:
      max-in-memory-size: 10MB

# id generator custom properties
id:
  bench:
    length: 7
  file:
    length: 25

#validation api custom properties
validation:
  bench:
    nameRegex: "[A-Za-z0-9]"
    nameRequired: true
    nameMinLength: 3
    nameMaxLength: 25
    descriptionRegex: "[A-Za-z0-9]"
    descriptionReqired: false
    descriptionMinLength: 0
    descriptionMaxLength: 255
    expirationMinDuration: 5s
    expirationMaxDuration: 60s

storage:
  local:
    root-dir: files
