server:
  port: 9000
  address: 0.0.0.0
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: filebench
      username: user
      password: password
      auto-index-creation: true
    redis:
      repositories:
        enabled: false
      hostname: localhost
      port: 6379
    codec:
      max-in-memory-size: 10MB
id:
  bench:
    length: 7
  file:
    length: 25
source:
  root-path: source


